global:
  hosts:
    domain: 192.168.1.12 # Change this to your real domain
    externalIP: "" # Optional: can be set if you're exposing via static IP
  
  appConfig:
    omniauth:
      enabled: false
  
  ingress:
    configureCertmanager: true
    tls:
      enabled: true
    class: nginx
    annotations:
      #kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod" # assumes you have a cluster issuer configured
  
  gitlab:
    rails:
      initial_root_password: "YourNewPassword123!"
  railsSecrets:
    cookieSecret: "a_very_long_random_string"
  gitlab:
    shell:
      authToken: "another_secure_random_string"

certmanager-issuer:
  email: g.groenendale@gmail.com
  install: true
  name: "letsencrypt-prod"
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretRef: "letsencrypt-prod"
  create: true
  selfSigned: false

nginx-ingress:
  enabled: true # Optional if you already have an ingress controller

gitlab:
  webservice:
    service:
      type: NodePort
      nodePort: 32800
    minReplicas: 1
    maxReplicas: 1

postgresql:
  install: true

redis:
  install: true

registry:
  enabled: true

gitlab-runner:
  install: true
