apiVersion: v1
kind: Config
clusters:
  - name: local-cluster
    cluster:
      server: https://192.168.1.11:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRJeE9EQTVOREl3SGhjTk1qVXdOekV3TWpBMU5UUXlXaGNOTXpVd056QTRNakExTlRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRJeE9EQTVOREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbFg0V1RqaVpIUkFBSXlqVjg2elRQMUhMdXlzOXNSbml3NzBCb0xDZEcKeDE3SVFNb3B4ajhvNTlUQmFhOURBRThLaElIa05nMldvSjloNmFpQ0VpSU5vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU1MZWZBUTNBSnljSDNmUGI5bFYzCldqTHVPYll3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnR3BiRUYxVEtoNHhpN3Z0UkdrVzhQcUV5UmhYY0xOZGYKb0lBeEtTeFAyK0lDSVFEU3UrZ2hMYW1ZVGx3UUgwS1RLQmhPcEZHZEZ0U00vRldlWDlxQitrVDBydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
users:
  - name: woodpecker-deployer
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IloyRnd4TG81MzAzQ3BibzVsLUJ3VUNFQ2dWWUxTaE92bmgtQklpSUQxcHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Indvb2RwZWNrZXItZGVwbG95ZXItc2VjcmV0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Indvb2RwZWNrZXItZGVwbG95ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI1ZDljOGRlMi0xYTEyLTQ5YjUtOGU1My1jMTUzNTNmYWQwODMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDp3b29kcGVja2VyLWRlcGxveWVyIn0.Vcxd-X7wlSUx1QW4PBDPUuoMhH-_MM6F5307qQkEiZce6SAdG803B1q6DsG1oPvnjBZPxgE0K6YaE2OBi_UNaLhMNezqJ03w5l0KkwhDEHr1MOXcTGHczmqpnGSgU5Zp7SRJAz5C7MFtJiBnXFZyS2e1D6qE1VimzuUxM-YPka7OtSxHkxNuFMPJxuyU6zooNb6R1LnzCghGpNR9SkwQ0nL1DrKwRfeli2W4ubNYTUeH_KiNBd4VHQkG6f8pEbG29HjIgT_z8xHoh4Q8FJuPUNJ5q6TuT0ROAry0d3jakw-N2M41QbiL6UBt4kET2S3u-BLmHQBeumRd5YVOmYsQ4g
contexts:
  - name: woodpecker
    context:
      cluster: local-cluster
      user: woodpecker-deployer
current-context: woodpecker
