# SSH Verification
#- name: Verify SSH is running
#  command: ss -tulpn | grep sshd
#  register: ssh_status
#  changed_when: false

- name: Check SSH config syntax
  command: sshd -t
  changed_when: false

- name: Display SSH version
  debug:
    msg: "SSH active ({{ ssh_status.stdout }})"
