- name: Provision Debian Router
  hosts: debian_router
  roles:
    - common
    - storage
    - bootloader
    - networking
    - bluetooth
    - network_storage
    - graphics
    - desktop
    - dev
    - cluster
    - ai
