- name: Install Libvirt and VM Tools
  become: true
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - cloud-image-utils
      - qemu-guest-agent
    state: present

- name: Enable Libvirt
  become: true
  command: sudo systemctl enable --now libvirtd

- name: Enable qemu-guest-agent
  become: true
  command: sudo systemctl enable --now qemu-guest-agent
